// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbCompania
    {
        public tbCompania()
        {
            tbBoletos = new HashSet<tbBoletos>();
        }

        public int comp_ID { get; set; }
        public string comp_Nombre { get; set; }
        public string muni_ID { get; set; }
        public string comp_Direccion { get; set; }
        public int? comp_Estado { get; set; }
        public int? comp_UsuarioCreador { get; set; }
        public DateTime? comp_FechaCreacion { get; set; }
        public int? comp_UsuarioModificador { get; set; }
        public DateTime? comp_FechaModificacion { get; set; }

        public virtual tbUsuarios comp_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios comp_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletos { get; set; }
    }
}