// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbHorarioshora_DestinoNavigation = new HashSet<tbHorarios>();
            tbHorarioshora_OrigenNavigation = new HashSet<tbHorarios>();
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string dept_ID { get; set; }
        public string dept_Descripcion { get; set; }
        public int? dept_Estado { get; set; }
        public int? dept_UsuarioCreador { get; set; }
        public DateTime? dept_FechaCreacion { get; set; }
        public int? dept_UsuarioModificador { get; set; }
        public DateTime? dept_FechaModificacion { get; set; }

        public virtual tbUsuarios dept_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios dept_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_DestinoNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_OrigenNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}