// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbBoletos = new HashSet<tbBoletos>();
        }

        public int pago_ID { get; set; }
        public string pago_Descripcion { get; set; }
        public int? pago_Estado { get; set; }
        public int? pago_UsuarioCreador { get; set; }
        public DateTime? pago_FechaCreacion { get; set; }
        public int? pago_UsuarioModificador { get; set; }
        public DateTime? pago_FechaModificacion { get; set; }

        public virtual tbUsuarios pago_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios pago_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletos { get; set; }
    }
}