// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuarioCreadorNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UsuarioModificadorNavigation = new HashSet<tbUsuarios>();
            tbBoletosbole_UsuarioCreadorNavigation = new HashSet<tbBoletos>();
            tbBoletosbole_UsuarioModificadorNavigation = new HashSet<tbBoletos>();
            tbCargoscarg_UsuarioCreadorNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UsuarioModificadorNavigation = new HashSet<tbCargos>();
            tbClientesclie_UsuarioCreadorNavigation = new HashSet<tbClientes>();
            tbClientesclie_UsuarioModificadorNavigation = new HashSet<tbClientes>();
            tbCompaniacomp_UsuarioCreadorNavigation = new HashSet<tbCompania>();
            tbCompaniacomp_UsuarioModificadorNavigation = new HashSet<tbCompania>();
            tbDepartamentosdept_UsuarioCreadorNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdept_UsuarioModificadorNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempl_UsuarioCreadorNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UsuarioModificadorNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesestciv_UsuarioCreadorNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestciv_UsuarioModificadorNavigation = new HashSet<tbEstadosCiviles>();
            tbHorarioshora_UsuarioCreadorNavigation = new HashSet<tbHorarios>();
            tbHorarioshora_UsuarioModificadorNavigation = new HashSet<tbHorarios>();
            tbMetodosPagopago_UsuarioCreadorNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagopago_UsuarioModificadorNavigation = new HashSet<tbMetodosPago>();
            tbMunicipiosmuni_UsuarioCreadorNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuarioModificadorNavigation = new HashSet<tbMunicipios>();
            tbPantallaspant_UsuarioCreadorNavigation = new HashSet<tbPantallas>();
            tbPantallaspant_UsuarioModificadorNavigation = new HashSet<tbPantallas>();
            tbRolesXPantallasroleXpant_UsuarioCreadorNavigation = new HashSet<tbRolesXPantallas>();
            tbRolesXPantallasroleXpant_UsuarioModificadorNavigation = new HashSet<tbRolesXPantallas>();
            tbRolesXPantallasusua = new HashSet<tbRolesXPantallas>();
            tbRolesrole_UsuarioCreadorNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuarioModificadorNavigation = new HashSet<tbRoles>();
            tbTerminalesterm_UsuarioCreadorNavigation = new HashSet<tbTerminales>();
            tbTerminalesterm_UsuarioModificadorNavigation = new HashSet<tbTerminales>();
        }

        public int usua_ID { get; set; }
        public string usua_Usuario { get; set; }
        public byte[] usua_Clave { get; set; }
        public int? usua_EsAdmin { get; set; }
        public int? empl_ID { get; set; }
        public int? usua_Estado { get; set; }
        public int? usua_UsuarioCreador { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificador { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios usua_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletosbole_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbBoletos> tbBoletosbole_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbCompania> tbCompaniacomp_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbCompania> tbCompaniacomp_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestciv_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestciv_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbHorarios> tbHorarioshora_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagopago_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagopago_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasroleXpant_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasroleXpant_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusua { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbTerminales> tbTerminalesterm_UsuarioCreadorNavigation { get; set; }
        public virtual ICollection<tbTerminales> tbTerminalesterm_UsuarioModificadorNavigation { get; set; }
    }
}