// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class VW_graficaSexo
    {
        public int? Masculino { get; set; }
        public int? Femenino { get; set; }
    }
}