// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class VW_graficaViaje
    {
        public string bole_hora_Destino_Nombre { get; set; }
        public int? Cantidad { get; set; }
    }
}