// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class VW_tbCargos
    {
        public int carg_ID { get; set; }
        public string carg_Nombre { get; set; }
        public int? carg_Estado { get; set; }
        public int? carg_UsuarioCreador { get; set; }
        public string carg_UsuarioCreador_Nombre { get; set; }
        public DateTime? carg_FechaCreacion { get; set; }
        public int? carg_UsuarioModificador { get; set; }
        public string carg_UsuarioModificador_Nombre { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }
    }
}