// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbBoletos
    {
        public int bole_ID { get; set; }
        public DateTime? bole_Fecha { get; set; }
        public int? term_ID { get; set; }
        public int? comp_ID { get; set; }
        public int? empl_ID { get; set; }
        public int? clie_ID { get; set; }
        public int? hora_ID { get; set; }
        public int? pago_ID { get; set; }
        public int? bole_Estado { get; set; }
        public int? bole_UsuarioCreador { get; set; }
        public DateTime? bole_FechaCreacion { get; set; }
        public int? bole_UsuarioModificador { get; set; }
        public DateTime? bole_FechaModificacion { get; set; }

        public virtual tbUsuarios bole_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios bole_UsuarioModificadorNavigation { get; set; }
        public virtual tbClientes clie { get; set; }
        public virtual tbCompania comp { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbHorarios hora { get; set; }
        public virtual tbMetodosPago pago { get; set; }
        public virtual tbTerminales term { get; set; }
    }
}