// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class tbRoles
    {
        public tbRoles()
        {
            tbRolesXPantallas = new HashSet<tbRolesXPantallas>();
        }

        public int role_ID { get; set; }
        public string role_Descripcion { get; set; }
        public int? role_Estado { get; set; }
        public int? role_UsuarioCreador { get; set; }
        public DateTime? role_FechaCreacion { get; set; }
        public int? role_UsuarioModificador { get; set; }
        public DateTime? role_FechaModificacion { get; set; }

        public virtual tbUsuarios role_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios role_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbRolesXPantallas> tbRolesXPantallas { get; set; }
    }
}