// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Terminal.Entities.Entities
{
    public partial class VW_tbBoletos2
    {
        public int bole_ID { get; set; }
        public DateTime? bole_Fecha { get; set; }
        public string bole_clie_Nombre_Completo { get; set; }
        public string bole_hora_Origen_Nombre { get; set; }
        public string bole_hora_Destino_Nombre { get; set; }
        public string comp_Nombre { get; set; }
    }
}