// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PruebaApi.Entities.Entities
{
    public partial class tbUsuarios
    {
        public int usua_ID { get; set; }
        public string usua_Usuario { get; set; }
        public byte[] usua_Clave { get; set; }
        public int? usua_EsAdmin { get; set; }
        public int? empl_ID { get; set; }
        public int? usua_Estado { get; set; }
        public int? usua_UsuarioCreador { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificador { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
    }
}