// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PruebaApi.Entities.Entities;

#nullable disable

namespace PruebaApi.DataAccess.Context
{
    public partial class DbterminalContext : DbContext
    {
        public DbterminalContext()
        {
        }

        public DbterminalContext(DbContextOptions<DbterminalContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbCompania> tbCompania { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbHorarios> tbHorarios { get; set; }
        public virtual DbSet<tbMetodosPago> tbMetodosPago { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolesXPantallas> tbRolesXPantallas { get; set; }
        public virtual DbSet<tbTerminales> tbTerminales { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.carg_ID)
                    .HasName("PK_term_tbCargos_carg_ID");

                entity.ToTable("tbCargos", "term");

                entity.Property(e => e.carg_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.carg_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.carg_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.carg_Nombre)
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbClientes>(entity =>
            {
                entity.HasKey(e => e.clie_ID)
                    .HasName("PK_term_tbPasajeros_psjr_ID");

                entity.ToTable("tbClientes", "term");

                entity.HasIndex(e => e.clie_DNI, "UQ_term_tbPasajeros_psjr_DNI")
                    .IsUnique();

                entity.Property(e => e.clie_Apellidos).HasMaxLength(200);

                entity.Property(e => e.clie_DNI)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.clie_Email).HasMaxLength(300);

                entity.Property(e => e.clie_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.clie_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.clie_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.clie_Nombres).HasMaxLength(200);

                entity.Property(e => e.clie_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.clie_Telefono)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<tbCompania>(entity =>
            {
                entity.HasKey(e => e.comp_ID)
                    .HasName("PK_term_tbCompania_comp_ID");

                entity.ToTable("tbCompania", "term");

                entity.Property(e => e.comp_ID).ValueGeneratedNever();

                entity.Property(e => e.comp_Direccion)
                    .HasMaxLength(300)
                    .IsUnicode(false);

                entity.Property(e => e.comp_Nombre)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.muni_ID)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.term_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.term_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.term_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.dept_ID)
                    .HasName("PK_gral_tbDepartamentos_dept_ID");

                entity.ToTable("tbDepartamentos", "gral");

                entity.Property(e => e.dept_ID)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.dept_Descripcion).HasMaxLength(200);

                entity.Property(e => e.dept_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.dept_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.dept_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.empl_ID)
                    .HasName("PK_term_tbEmpleados_empl_ID");

                entity.ToTable("tbEmpleados", "term");

                entity.HasIndex(e => e.empl_DNI, "UQ_term_tbEmpleados_empl_DNI")
                    .IsUnique();

                entity.Property(e => e.empl_DNI)
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.empl_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.empl_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.empl_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.empl_FechaNacimiento).HasColumnType("date");

                entity.Property(e => e.empl_PrimerApellido).HasMaxLength(100);

                entity.Property(e => e.empl_PrimerNombre).HasMaxLength(100);

                entity.Property(e => e.empl_SegundoApellido).HasMaxLength(100);

                entity.Property(e => e.empl_SegundoNombre).HasMaxLength(100);

                entity.Property(e => e.empl_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.empl_Telefono)
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.muni_ID)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.carg)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.carg_ID)
                    .HasConstraintName("FK_term_tbEmpleados_tbCargos_carg_ID");

                entity.HasOne(d => d.estciv)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.estciv_ID)
                    .HasConstraintName("FK_term_tbEmpleados_gral_tbEstadosCiviles_estciv_ID");

                entity.HasOne(d => d.muni)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.muni_ID)
                    .HasConstraintName("FK_term_tbEmpleados_gral_tbMunicipios_muni_ID");
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.estciv_ID)
                    .HasName("PK_gral_tbEstadosCiviles_estciv_ID");

                entity.ToTable("tbEstadosCiviles", "gral");

                entity.Property(e => e.estciv_Descripcion)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.estciv_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.estciv_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.estciv_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbHorarios>(entity =>
            {
                entity.HasKey(e => e.hora_ID)
                    .HasName("PK_term_tbHorarios_hora_ID");

                entity.ToTable("tbHorarios", "term");

                entity.Property(e => e.hora_Destino)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.hora_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.hora_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.hora_FechaLlegada).HasColumnType("datetime");

                entity.Property(e => e.hora_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.hora_FechaSalida).HasColumnType("datetime");

                entity.Property(e => e.hora_Origen)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.hora_DestinoNavigation)
                    .WithMany(p => p.tbHorarioshora_DestinoNavigation)
                    .HasForeignKey(d => d.hora_Destino)
                    .HasConstraintName("FK_term_tbHorarios_hora_Destino_gral_tbDepartamentos_dept_ID");

                entity.HasOne(d => d.hora_OrigenNavigation)
                    .WithMany(p => p.tbHorarioshora_OrigenNavigation)
                    .HasForeignKey(d => d.hora_Origen)
                    .HasConstraintName("FK_term_tbHorarios_hora_Origen_gral_tbDepartamentos_dept_ID");
            });

            modelBuilder.Entity<tbMetodosPago>(entity =>
            {
                entity.HasKey(e => e.pago_ID)
                    .HasName("PK_gral_tbMetodosPago_pago_ID");

                entity.ToTable("tbMetodosPago", "gral");

                entity.Property(e => e.pago_Descripcion).HasMaxLength(200);

                entity.Property(e => e.pago_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.pago_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.pago_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbMunicipios>(entity =>
            {
                entity.HasKey(e => e.muni_ID)
                    .HasName("PK_gral_tbMunicipios_muni_ID");

                entity.ToTable("tbMunicipios", "gral");

                entity.Property(e => e.muni_ID)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.dept_ID)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.muni_Descripcion).HasMaxLength(200);

                entity.Property(e => e.muni_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.muni_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.muni_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.dept)
                    .WithMany(p => p.tbMunicipios)
                    .HasForeignKey(d => d.dept_ID)
                    .HasConstraintName("FK_gral_tbMunicipios_tbDepartamentos_dept_ID");
            });

            modelBuilder.Entity<tbPantallas>(entity =>
            {
                entity.HasKey(e => e.pant_ID)
                    .HasName("PK_acce_tbPantallas_pant_ID");

                entity.ToTable("tbPantallas", "acce");

                entity.Property(e => e.pant_Descripcion)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.pant_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.pant_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.pant_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.role_ID)
                    .HasName("PK_acce_tbRoles_role_ID");

                entity.ToTable("tbRoles", "acce");

                entity.Property(e => e.role_Descripcion)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.role_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.role_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.role_FechaModificacion).HasColumnType("datetime");
            });

            modelBuilder.Entity<tbRolesXPantallas>(entity =>
            {
                entity.HasKey(e => e.roleXpant_ID)
                    .HasName("PK_acce_tbRolesXPantallas_roleXpant_ID");

                entity.ToTable("tbRolesXPantallas", "acce");

                entity.Property(e => e.roleXpant_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.roleXpant_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.roleXpant_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.pant)
                    .WithMany(p => p.tbRolesXPantallas)
                    .HasForeignKey(d => d.pant_ID)
                    .HasConstraintName("FK_acce_tbRolesXPantallas_tbPantallas_pant_ID");

                entity.HasOne(d => d.role)
                    .WithMany(p => p.tbRolesXPantallas)
                    .HasForeignKey(d => d.role_ID)
                    .HasConstraintName("FK_acce_tbRolesXPantallas_tbRoles_role_ID");
            });

            modelBuilder.Entity<tbTerminales>(entity =>
            {
                entity.HasKey(e => e.term_ID)
                    .HasName("PK_term_tbTerminales_term_ID");

                entity.ToTable("tbTerminales", "term");

                entity.Property(e => e.muni_ID)
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.term_DireccionExacta)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.term_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.term_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.term_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.term_Nombre)
                    .HasMaxLength(300)
                    .IsUnicode(false);

                entity.HasOne(d => d.muni)
                    .WithMany(p => p.tbTerminales)
                    .HasForeignKey(d => d.muni_ID)
                    .HasConstraintName("FK_term_tbTerminales_gral_tbMunicipios_muni_ID");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.usua_ID)
                    .HasName("PK_acce_tbUsuarios_usua_ID");

                entity.ToTable("tbUsuarios", "acce");

                entity.HasIndex(e => e.usua_Usuario, "UQ_acce_tbUsuarios_usua_Usuario")
                    .IsUnique();

                entity.Property(e => e.usua_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.usua_FechaCreacion)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.usua_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.usua_Usuario).HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}